name: Deployment Workflow

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    ‐ name: build-push
      uses: docker/build-push-action@v2
      with:
        registry: myregistry
        repository: myorg/myrepo
        tags: velith/firebase-action:1.2